print("What is your name human?")
name = input()
print("How old are you (in years)?")
age = input()
print("How tall are you (in meters)?")
height = input()
print("How much do you weigh (in kilograms)?")
weight = input()
print(" " + name + " you are"  + age + " years old and your bmi is ") 